# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calib <- function(Y, C, Z, mu_input, mu_dim, mu0_input, mu0_dim) {
    .Call('MPK_calib', PACKAGE = 'MPK', Y, C, Z, mu_input, mu_dim, mu0_input, mu0_dim)
}

fit <- function(Y, C, prior, mcmc, state) {
    .Call('MPK_fit', PACKAGE = 'MPK', Y, C, prior, mcmc, state)
}

